Update ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -19,7 +19,6 @@ jobs:
       - name: Install dependencies
         run: |
           pip install mlflow
-          # echo "MLFLOW_TRACKING_URI=${{ vars.MLFLOW_TRACKING_URI }}" >> $GITHUB_ENV
           echo "MLFLOW_TRACKING_USERNAME=${{ secrets.MLFLOW_TRACKING_USERNAME }}" >> $GITHUB_ENV
           echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.MLFLOW_TRACKING_PASSWORD }}" >> $GITHUB_ENV
 
@@ -44,27 +43,30 @@ jobs:
           name: artifacts
           path: MLProject/mlruns/0/${{ env.RUN_ID }}/artifacts
 
-      # - name: Build Docker Model
-      #   run: |
-      #     MODEL_PATH="MLProject/mlruns/0/${{ env.RUN_ID }}/artifacts/model"
-          
-      #     if [ ! -d "$MODEL_PATH" ]; then
-      #       echo "Model artifacts not found at $MODEL_PATH"
-      #       exit 1
-      #     fi
-
-      #     mlflow models build-docker \
-      #       --model-uri "$MODEL_PATH" \
-      #       --name "hiring_prediction_model"\
-      #       --enable-mlserver
+      - name: List files for debug
+        run: |
+          echo "Root directory:"
+          ls -la
+          echo "MLProject directory:"
+          ls -la MLProject
 
       - name: Build Docker Model
         run: |
           echo "Using RUN_ID: ${{ env.RUN_ID }}"
           export MLFLOW_TRACKING_URI=./MLProject/mlruns
-          DOCKER_BUILDKIT=1 docker build -t diamond_price_model MLProject
 
-          
+          # Ganti path ke Dockerfile sesuai lokasi sebenarnya
+          if [ -f MLProject/Dockerfile ]; then
+            echo "Dockerfile found in MLProject"
+            DOCKER_BUILDKIT=1 docker build -t diamond_price_model MLProject
+          elif [ -f Dockerfile ]; then
+            echo "Dockerfile found in root"
+            DOCKER_BUILDKIT=1 docker build -t diamond_price_model -f Dockerfile .
+          else
+            echo "Dockerfile not found!"
+            exit 1
+          fi
+
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
@@ -72,7 +74,9 @@ jobs:
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
       - name: Tag Docker Image
-        run: docker tag hiring_prediction_model ${{ vars.DOCKERHUB_USERNAME }}/diamond_price_model:latest
+        run: |
+          docker tag diamond_price_model ${{ vars.DOCKERHUB_USERNAME }}/diamond_price_model:latest
 
       - name: Push Docker Image
-        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/diamond_price_model:latest
+        run: |
+          docker push ${{ vars.DOCKERHUB_USERNAME }}/diamond_price_model:latest
